server:
  port: 8080
  servlet:
    context-path: 
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    url: jdbc:mysql://localhost:3306/animal?serverTimezone=Asia/Seoul
    username: animal
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
        
    
file:
  path: C:/src/springbootWork/springboot-nr/media/